FROM python:3.11-slim

# Pasta de trabalho dentro do container
WORKDIR /app

# Copia tudo do repositório para dentro do container
COPY . .

# Instala as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Porta interna que o gunicorn vai usar
EXPOSE 8000

# Comando para iniciar a app em produção
CMD ["gunicorn", "app:app", "--bind", "0.0.0.0:8000"]
